name: Sync to Hugging Face Hub

on:
  push:
    branches:
      - main  # or master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install git-lfs
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git clone https://huggingface.co/vikasgautam2003/email_spams_detector
          cd email_spams_detector

          # Copy files from GitHub repo to HF repo
          rsync -av --exclude='.git' ../ .

          git add .
          git commit -m "Sync from GitHub" || echo "No changes to commit"
          git push https://user:$HF_TOKEN@huggingface.co/vikasgautam2003/email_spams_detector main
